import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'

export default function Home() {
  const dispatch = useDispatch();
  const movies = useSelector(store => store.movieReducer);
  // Renders the entire app on the DOM
  function getMovies() {
    axios.get(`http://localhost:8080/api/v1/movies`).then((response) => {
      console.log('This is response: ', response.data);
      dispatch({
        type: 'SET_MOVIES',
        payload: response.data
      });
    }).catch((err) => {
      console.log('Erron GET', err);
    });
  }

  useEffect(() => {
    getMovies();
  }, []);


  return (
    <>
      <Head>
        <title>Vetter Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Hello</h1>
          {movies && movies.map(movie => {
            return (
              <div key={movie.imdbId} className={styles.description}>
                <h3>{movie.title}</h3>
                <Image src={movie.poster} alt={movie.title} width={180} height={50}/>
              </div>
            )
          })}
        </div>
      </main>
    </>
  )
}
